apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: database
      image: mysql:5.7
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
  volumes:
    - name: mysql-volume
      hostPath:
        path: /var/lib/mysql