version: '3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./app:/var/www/html"
    links:
      - database

  database:
    image: mysql:5.7
    restart: always
    container_name: my_sql
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
