apiVersion: v1
kind: Pod
metadata:
  name: php-pod
spec:
  containers:
    - name: php
      image: php:8.2-apache
      ports:
        - containerPort: 80
        - containerPort: 443
      volumeMounts:
        - name: php-volume
          mountPath: /var/www/html
  volumes:
    - name: php-volume
      hostPath:
        path: ".:/var/www/html"